import { LegalDocument, type LegalSection } from '@/components/legal-document';

const sections: LegalSection[] = [
  { heading: 'Information We Collect', paragraphs: ['JobOps may collect account and contractor information such as your name, email address, phone number, authentication identifiers, role, profile image, account status, and communication preferences. We collect information you submit about customers, properties, work orders, schedules, job notes, invoice amounts, and work status.'], bullets: ['Uploaded files and content, including photographs, videos, invoices, receipts, and related file metadata.', 'Device, browser, application, diagnostic, security, and usage information needed to operate, protect, and troubleshoot JobOps.', 'Contact and communication information, including SMS consent status, consent timestamp, messages requested through JobOps, and support communications.'] },
  { heading: 'How We Use Information', paragraphs: ['Descode LLC uses information to provide and secure JobOps, authenticate users, manage contractor access, create and assign work orders, coordinate schedules, store job records, deliver service communications, maintain audit history, troubleshoot problems, and improve reliability. We do not use JobOps transactional messaging for promotional or third-party marketing.'] },
  { heading: 'SMS Communications', paragraphs: ['If you separately opt in, Descode LLC may send recurring transactional text messages through JobOps, including verification codes, account invitations, work-order assignments, scheduling information, work-order changes, status updates, and service-related notifications. Message frequency varies. Message and data rates may apply.', 'Reply STOP to unsubscribe from non-essential transactional messages. Reply HELP for assistance. Consent to receive SMS messages is not a condition of purchase. Authentication codes may be sent when you specifically request phone-based authentication.', 'No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. Text messaging originator opt-in data and consent will not be shared with any third parties.'] },
  { heading: 'Service Providers and Disclosure', paragraphs: ['Service providers may process information only as needed to operate JobOps, such as hosting, authentication, database, file storage, email, SMS delivery, security, and technical-support providers. Descode LLC may also disclose information when reasonably necessary to comply with applicable law, protect users or the service, investigate misuse, or complete a business transaction subject to appropriate safeguards.'] },
  { heading: 'Security', paragraphs: ['Descode LLC uses reasonable administrative, technical, and organizational measures designed to protect information. No internet, mobile, or storage system can be guaranteed completely secure, and users must protect their credentials and devices.'] },
  { heading: 'Retention', paragraphs: ['We retain information for as long as reasonably needed to provide JobOps, maintain business and work-order records, meet operational or legal obligations, resolve disputes, and protect the service. Retention periods vary based on the type of record and why it is processed.'] },
  { heading: 'Your Choices and Rights', paragraphs: ['You may update certain profile information in JobOps, ask your JobOps administrator to correct account information, withdraw SMS consent by replying STOP, or request assistance regarding your information. Depending on where you live, you may have additional rights under applicable law. We may need to verify your identity before completing a request.'] },
  { heading: 'Children’s Privacy', paragraphs: ['JobOps is a business application for authorized contractors and administrators and is not directed to children under 13. Descode LLC does not knowingly collect personal information from children under 13 through JobOps.'] },
  { heading: 'Changes to This Policy', paragraphs: ['Descode LLC may update this Privacy Policy as JobOps changes. The updated policy will be posted with a revised effective date. Material changes may also be communicated through the application or another appropriate channel.'] },
  { heading: 'Contact Us', paragraphs: ['For privacy questions, SMS help, or requests concerning this policy, contact Descode LLC at: [REPLACE WITH DESCODE LLC SUPPORT EMAIL].'] },
];

export default function PrivacyScreen() { return <LegalDocument title="Privacy Policy" effectiveDate="August 29, 2026" intro="Descode LLC operates JobOps, a field-operations application for authorized contractors and administrators. This Privacy Policy explains how information is collected, used, disclosed, and protected when you use JobOps." sections={sections} />; }
