import { LegalDocument, type LegalSection } from '@/components/legal-document';

const sections: LegalSection[] = [
  { heading: 'Permitted Use', paragraphs: ['Descode LLC grants authorized users a limited, revocable, non-transferable right to use JobOps for legitimate business operations. You may not misuse the service, interfere with its operation, attempt unauthorized access, reverse engineer protected portions, introduce malicious code, or use JobOps unlawfully.'] },
  { heading: 'Accounts and User Responsibilities', paragraphs: ['You must provide accurate account information, keep credentials confidential, protect devices used to access JobOps, and promptly report suspected unauthorized access. You are responsible for activity performed through your account and for following your organization’s work and safety procedures.'] },
  { heading: 'Work-Order Information', paragraphs: ['Users are responsible for the accuracy, completeness, authorization, and lawful use of customer, property, scheduling, work-order, job-note, invoice, and completion information entered into JobOps. JobOps is an operational recordkeeping tool and does not replace professional judgment, inspections, safety procedures, contracts, or legally required records.'] },
  { heading: 'Uploaded Content', paragraphs: ['You retain responsibility for photographs, videos, documents, notes, invoices, and other content you upload. You represent that you have the right to submit that content and grant Descode LLC permission to host, process, reproduce, and transmit it as needed to operate JobOps. Do not upload unlawful, harmful, or unrelated content.'] },
  { heading: 'SMS Terms', paragraphs: ['If you separately opt in, Descode LLC may send recurring transactional text messages through JobOps, including verification codes, account invitations, work-order assignments, scheduling information, work-order changes, status updates, and service-related notifications. Message frequency varies. Message and data rates may apply.', 'Reply STOP to opt out of non-essential transactional messages. Reply HELP for assistance. Consent to receive SMS messages is not a condition of purchase. Mobile carriers are not liable for delayed or undelivered messages. Your carrier’s terms and charges may apply.'] },
  { heading: 'Service Availability', paragraphs: ['JobOps may occasionally be unavailable because of maintenance, connectivity, third-party services, security events, or circumstances outside Descode LLC’s reasonable control. Features may change or be discontinued. Descode LLC does not guarantee uninterrupted, error-free, or loss-free operation.'] },
  { heading: 'Suspension and Termination', paragraphs: ['Descode LLC or an authorized JobOps administrator may suspend or terminate access when an account is inactive, unauthorized, insecure, misused, or no longer needed. Upon termination, your right to use JobOps ends, although records may be retained as described in the Privacy Policy or as required for legitimate business purposes.'] },
  { heading: 'Disclaimers', paragraphs: ['JobOps is provided on an “as is” and “as available” basis to the extent permitted by applicable law. Descode LLC disclaims warranties that may lawfully be disclaimed, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Nothing in these Terms excludes rights that cannot legally be excluded.'] },
  { heading: 'Limitation of Liability', paragraphs: ['To the extent permitted by applicable law, Descode LLC will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profits, data, business, or goodwill arising from use of or inability to use JobOps. Any limitation applies only to the extent enforceable under applicable law.'] },
  { heading: 'Changes to These Terms', paragraphs: ['Descode LLC may update these Terms as JobOps changes. Updated Terms will be posted with a revised effective date. Continued use after an update means you accept the revised Terms to the extent permitted by applicable law.'] },
  { heading: 'Contact', paragraphs: ['For questions about these Terms or SMS assistance, contact Descode LLC at: [REPLACE WITH DESCODE LLC SUPPORT EMAIL].'] },
];

export default function TermsScreen() { return <LegalDocument title="Terms of Service" effectiveDate="August 29, 2026" intro="These Terms of Service govern access to and use of JobOps, an application operated by Descode LLC. By using JobOps, you agree to these Terms and the JobOps Privacy Policy." sections={sections} />; }
