import { Ionicons } from '@expo/vector-icons';
import { ImageBackground } from 'expo-image';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';

const YELLOW = '#FFF200'; const NAVY = '#003366'; const BLUE = '#1E67B2'; const INK = '#172033'; const PAPER = '#FFFFFF'; const MUTED = '#566273';
type CompletedOrder = { id: string; work_order_number: string; title: string; completed_at: string | null; properties: { address_line_1: string; city: string; state: string } | null };

export default function CompletedScreen() {
  const router = useRouter();
  const [orders, setOrders] = useState<CompletedOrder[]>([]); const [isLoading, setIsLoading] = useState(true);
  const loadCompletedOrders = useCallback(async () => {
    setIsLoading(true); const { data: authData } = await supabase.auth.getUser();
    if (!authData.user) { setOrders([]); setIsLoading(false); return; }
    const { data: contractor } = await supabase.from('contractors').select('id').eq('auth_user_id', authData.user.id).eq('is_active', true).single();
    if (!contractor) { setOrders([]); setIsLoading(false); return; }
    const { data: assignments } = await supabase.from('work_order_assignments').select('work_order:work_orders!inner(id, work_order_number, title, completed_at, status, properties(address_line_1, city, state))').eq('contractor_id', contractor.id).is('unassigned_at', null).eq('work_order.status', 'completed');
    setOrders((assignments ?? []).map((assignment) => assignment.work_order).filter(Boolean) as unknown as CompletedOrder[]); setIsLoading(false);
  }, []);
  useFocusEffect(useCallback(() => { void loadCompletedOrders(); }, [loadCompletedOrders]));
  return <SafeAreaView style={styles.safeArea} edges={['top']}><ScrollView contentContainerStyle={styles.content}><ImageBackground source={require('@/assets/images/dark-blue-particle-texture-background.jpg')} style={styles.header} contentFit="cover"><View><Text style={styles.kicker}>MARTY WRIGHT</Text><Text style={styles.title}>Complete Work Order</Text></View><View style={[styles.icon, { backgroundColor: 'transparent', borderRadius: 0 }]}><Ionicons name="checkmark-done-outline" size={28} color={YELLOW} /></View></ImageBackground><View style={styles.intro}><Ionicons name="archive-outline" size={22} color={NAVY} /><View style={styles.introCopy}><Text style={styles.introTitle}>Completed Work History</Text><Text style={styles.introText}>Your completed work orders remain available here.</Text></View></View><Text style={styles.count}>{isLoading ? 'LOADING...' : `${orders.length} COMPLETED ORDER${orders.length === 1 ? '' : 'S'}`}</Text>{!isLoading && orders.length === 0 && <View style={styles.empty}><Ionicons name="checkmark-done-outline" size={27} color={BLUE} /><Text style={styles.emptyText}>No completed work orders yet.</Text></View>}{orders.map((order) => <TouchableOpacity key={order.id} style={styles.card} onPress={() => router.push({ pathname: '/work-order/[id]', params: { id: order.id } })}><View style={styles.cardTop}><Text style={styles.status}>COMPLETED</Text><Text style={styles.id}>#{order.work_order_number}</Text></View><Text style={styles.orderTitle}>{order.title}</Text><Text style={styles.address}>{formatAddress(order.properties)}</Text><View style={styles.footer}><Text style={styles.footerLabel}>COMPLETED {order.completed_at ? new Date(order.completed_at).toLocaleDateString() : ''}</Text><Ionicons name="arrow-forward-circle" size={20} color={BLUE} /></View></TouchableOpacity>)}</ScrollView></SafeAreaView>;
}
function formatAddress(property: CompletedOrder['properties']) { return property ? `${property.address_line_1}, ${property.city}, ${property.state}` : 'Address unavailable'; }
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: 'transparent' }, content: { flexGrow: 1, backgroundColor: PAPER, paddingHorizontal: 20, paddingBottom: 30 }, header: { backgroundColor: NAVY, marginHorizontal: -20, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 25, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { color: YELLOW, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginBottom: 8 }, title: { color: PAPER, fontSize: 28, fontWeight: '800' }, icon: { width: 42, height: 42, backgroundColor: '#1E67B2', borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, intro: { backgroundColor: '#EAF1F8', padding: 16, marginTop: 22, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 6 }, introCopy: { flex: 1 }, introTitle: { color: INK, fontSize: 14, fontWeight: '800', marginBottom: 4 }, introText: { color: MUTED, fontSize: 11 }, count: { color: MUTED, fontSize: 10, fontWeight: '900', letterSpacing: 1.2, marginTop: 26, marginBottom: 12 }, empty: { alignItems: 'center', paddingTop: 80 }, emptyText: { color: MUTED, marginTop: 12 }, card: { backgroundColor: PAPER, borderWidth: 1, borderColor: '#D7E1EC', padding: 17, marginBottom: 12, borderRadius: 6 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, status: { color: BLUE, fontSize: 10, fontWeight: '900' }, id: { color: MUTED, fontSize: 10 }, orderTitle: { color: INK, fontSize: 18, fontWeight: '800', marginTop: 15 }, address: { color: MUTED, fontSize: 12, marginTop: 10 }, footer: { borderTopWidth: 1, borderTopColor: '#E2EAF2', marginTop: 16, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, footerLabel: { color: INK, fontSize: 10, fontWeight: '800' }, });
